// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using NTCore.DataAccess;
using NTCore.DataModel;
using System;

namespace NTCore.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("NTCore.DataModel.Entities.SiteInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<DateTime>("AddDate")
                        .HasColumnName("AddDate");

                    b.Property<int>("AddUserId")
                        .HasColumnName("AddUserId");

                    b.Property<string>("Copyright")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("DataSort")
                        .HasColumnName("DataSort");

                    b.Property<int>("DataState")
                        .HasColumnName("DataState");

                    b.Property<DateTime>("ExpireDate");

                    b.Property<bool>("IsShow")
                        .HasColumnName("IsShow");

                    b.Property<int>("LastUpdateUserId")
                        .HasColumnName("LastUpdateUserId");

                    b.Property<string>("LogoUrl");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("MetaKeywords")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("SiteState");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("NF_Site");
                });

            modelBuilder.Entity("NTCore.DataModel.Entities.UserInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<DateTime>("AddDate")
                        .HasColumnName("AddDate");

                    b.Property<int>("AddUserId")
                        .HasColumnName("AddUserId");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<bool>("Confirmed");

                    b.Property<int>("DataSort")
                        .HasColumnName("DataSort");

                    b.Property<int>("DataState")
                        .HasColumnName("DataState");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsChecked");

                    b.Property<bool>("IsShow")
                        .HasColumnName("IsShow");

                    b.Property<int>("LastUpdateUserId")
                        .HasColumnName("LastUpdateUserId");

                    b.Property<int>("Level");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("SiteId")
                        .HasColumnName("SiteId");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnName("UpdateDate");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("NF_User");
                });
#pragma warning restore 612, 618
        }
    }
}
