// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OpenCqrs.Store.EF;
using System;

namespace OpenCqrs.Store.EF.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    partial class DomainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OpenCqrs.Store.EF.Entities.AggregateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("DomainAggregate");
                });

            modelBuilder.Entity("OpenCqrs.Store.EF.Entities.CommandEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AggregateId");

                    b.Property<string>("Data");

                    b.Property<string>("Source");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("Type");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.ToTable("DomainCommand");
                });

            modelBuilder.Entity("OpenCqrs.Store.EF.Entities.EventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AggregateId");

                    b.Property<long>("CommandId");

                    b.Property<string>("Data");

                    b.Property<int>("Sequence");

                    b.Property<string>("Source");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("Type");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.ToTable("DomainEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
